DROP TABLE IF EXISTS `operation_log`;
CREATE TABLE `operation_log`
(
    `id` bigint(20) unsigned NOT NULL COMMENT '主键ID（雪花算法，由应用生成）',
    `operation`       varchar(255) NOT NULL COMMENT '操作描述',
    `method`          varchar(500)  DEFAULT NULL COMMENT '方法全限定名（类名#方法名）',
    `request_path`    varchar(500)  DEFAULT NULL COMMENT '请求路径',
    `request_method`  varchar(10)   DEFAULT NULL COMMENT '请求方式（GET/POST/PUT/DELETE等）',
    `params`          text COMMENT '方法入参（JSON格式）',
    `result`          text COMMENT '方法返回值（JSON格式）',
    `exception`       varchar(1000) DEFAULT NULL COMMENT '异常信息',
    `exception_stack` text COMMENT '异常堆栈',
    `user_id`         bigint(20) DEFAULT NULL COMMENT '操作者用户ID',
    `user_name`       varchar(100)  DEFAULT NULL COMMENT '操作者用户名',
    `client_ip`       varchar(50)   DEFAULT NULL COMMENT '客户端IP地址',
    `user_agent`      varchar(500)  DEFAULT NULL COMMENT '请求来源（User-Agent）',
    `operation_time`  datetime     NOT NULL COMMENT '操作时间',
    `cost_time`       bigint(20) DEFAULT NULL COMMENT '方法执行耗时（毫秒）',
    `status`          varchar(20)  NOT NULL COMMENT '操作状态（SUCCESS/FAILED）',
    `module`          varchar(100)  DEFAULT NULL COMMENT '业务模块',
    `business_type`   varchar(100)  DEFAULT NULL COMMENT '业务类型',
    `ext_info`        text COMMENT '扩展字段（JSON格式）',
    `trace_id`        varchar(100)  DEFAULT NULL COMMENT '调用链追踪ID',
    `span_id`         varchar(100)  DEFAULT NULL COMMENT '调用链跨度ID',
    PRIMARY KEY (`id`),
    KEY               `idx_operation_time` (`operation_time`),
    KEY               `idx_user_id` (`user_id`),
    KEY               `idx_status` (`status`),
    KEY               `idx_module` (`module`),
    KEY               `idx_trace_id` (`trace_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='操作日志表';